### ISSUE TITLE
Add link to YouTube video

### ISSUE THREAD

**Issue by sloede** [trixi-framework/talk-2021-juliacon#3]
Should we add a link to the YouTube video and/or other resources (e.g. conference agenda entry) to the README? I think both would be useful: The video, for people just looking for the video, and the conference agenda to have two-way linkage.

**Comment by ranocha** [comment]
> Should we add a link to the YouTube video

Sounds good to me. Feel free to make a PR

> conference agenda entry

That link seems to be https://live.juliacon.org/talk/VAGFD7. Thus, I'm not sure whether it will be permanent or not (there is nothing specific to JuliaCon *2021* in the URL).

**Comment by sloede** [comment]
> > Should we add a link to the YouTube video
> 
> Sounds good to me. Feel free to make a PR

Will do, likely not before the Trixi meeting tomorrow.

> > conference agenda entry
> 
> That link seems to be https://live.juliacon.org/talk/VAGFD7. Thus, I'm not sure whether it will be permanent or not (there is nothing specific to JuliaCon _2021_ in the URL).

It is not, as per @aviks:
> This URL will be live till next JuliaCon. After that, it will be archived somewhere. But I'm not sure where exactly.

Thus I think we should just include the link to the video.
