### ISSUE TITLE
YouTube time stamps

### ISSUE THREAD

**Issue by sloede** [trixi-framework/talk-2021-juliacon#4]
I've tried to create timestamps for the [JuliaCon YouTube time stamps repo](https://github.com/JuliaCommunity/YouTubeVideoTimestamps). I propose to open an issue with the following content:

YouTube: https://www.youtube.com/watch?v=hoViWRAhCBE
Talk repo: https://github.com/trixi-framework/talk-2021-juliacon
Package repo: https://github.com/trixi-framework/Trixi.jl

00:08 Welcome
00:46 Motivation and goals
03:32 Current state and simulation examples
05:47 Live demo: Introduction
06:36 Live demo: Creating a Trixi simulation from scratch
09:49 Live demo: Using a different initial condition
10:46 Live demo: Adaptive mesh refinement
12:22 Live demo: Advanced usage
14:08 Evaluating Julia for simulation science
14:15 Performance
17:36 Ease of use
18:03 Binary dependencies
19:04 Reproducibility
19:38 Extendability
22:44 Conclusions and outlook

@ranocha It would be great if you could check if the time stamps work for you as well, and if you would change anything (remove/add entries, rename titles etc.)

**Comment by ranocha** [comment]
Sounds good to me. Feel free to go ahead as proposed

**Comment by sloede** [comment]
Done in https://github.com/JuliaCommunity/YouTubeVideoTimestamps/issues/72

**Comment by ranocha** [comment]
Thanks! Can we close this?
